### ISSUE TITLE
112页标签页组件代码有错误

### ISSUE THREAD

**Issue by kangkai124** [icarusion/vue-book#21]
按照示例代码敲了一遍，发现设置的默认选中的标签没起作用，发现问题应该出在下面这里。
在index.html 中：
```
<tabs v-model="activeKey">
...
```
v-model 是用于表单类元素的数据双向绑定，而 tabs 组件内部并没有用到表单元素。
所以应该是改为 v-bind 绑定：
```
<tabs :value="activeKey">
```
以上为本人的个人理解，并手敲了一遍，改后运行没有问题。如有不合理之处，麻烦大大帮忙指出，谢谢。

**Comment by icarusion** [comment]
请查看组件使用 `v-model` 的用法。
