### ISSUE TITLE
P96异步更新队列疑问

### ISSUE THREAD

**Issue by A-Tu9371** [icarusion/vue-book#30]
书上说Vue会根据浏览器环境优先使用原生的Promise.then和MutationObserver，但是vue.js官方文档却是‘Vue 在内部尝试对异步队列使用原生的 Promise.then 和 MessageChannel‘，请问MutationObserver与MessageChannel有何区别，为什么两处的出入这么大？

**Comment by icarusion** [comment]
你看一下 Vue.js 的版本和书中的 Vue.js 版本。

**Comment by shadowprompt** [comment]
看下源码就知道了
