### ISSUE TITLE
P188页webpack版本过旧，教程有些过时

### ISSUE THREAD

**Issue by sophiayang1997** [icarusion/vue-book#37]
现在webpack版本是4.x了，很多命令不一样，比如webpack-cli的问题困扰了很久，请问什么时候跟上新版的教程？

**Comment by icarusion** [comment]
出版物不同文档，无法及时更新到。如果以后出第二版，会考虑更新到最新版的。

**Comment by sophiayang1997** [comment]
好~嘿嘿不过新手最好是按照仓库代码上的package.json的版本去安装各种依赖，不然会报错~（此书真的很棒!）

**Comment by sophiayang1997** [comment]
好~建议新手还是看着这个仓库的依赖版本去安装依赖，不然会报错（此书写的非常好！）
